=== Jonracwzl/aimfree_models/MoRo_Schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"name": "Mobile_Robot",
	"revision": "0.0.1",
	"description": "Schema of mobile Robot",
	"id": "123",
	"properties": {
		"name": {
			"$ref": "#/definitions/name"
		},
		"revision": {
			"type": "string",
			"pattern": "^\\d*\\.\\d*\\.\\d*$"
		},
		"description": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"submodels": {
			"properties": {
				"capabilities":{
				"$ref": "https://raw.githubusercontent.com/Jonracwzl/aimfree_models/master/capabilities_schema.json#"
				},
				"location": {
					"$ref": "https://raw.githubusercontent.com/Jonracwzl/aimfree_models/master/location.json#"
				},
				"state": {
					"$ref": "https://raw.githubusercontent.com/Jonracwzl/aimfree_models/master/state.json#"
				},
				"light": {
					"$ref": "https://raw.githubusercontent.com/Jonracwzl/aimfree_models/master/light.json#"
				}
			},
			"required": [
				"light",
				"location",
				"state"
			]
		}
	},
	"required": [
		"submodels"
	],
	"definitions": {
		"name": {
			"type": "string",
			"pattern": "^[A-Za-z_][A-Za-z0-9_]*$",
			"minLength": 3
		}
	}
}

=== Jonracwzl/aimfree_models/MoRo1.json
{
	"name": "MoRo1",
	"revision": "0.0.1",
	"description": "Mobile Robot 1",
	"submodels": {
		"capabilities": {
			"drilling": {},
			"grab": {},
			"move": {}
		},
		"state": {
			"state": "idle"
		},
		"location": {
			"pose": {
				"location": {
					"x": 10,
					"y": 20,
					"z": 30
				},
				"confidence": 0.3
			}
		},
		"light": {
			"name": "light1",
			"light_on": true
		},
		"light": {
			"name": "light2",
			"light_on": true
		}
	}
}
