=== Jonracwzl/aimfree_models/Ressource_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"type": "object",
	"properties": {
		"name": {
			"$ref": "#/definitions/name"
		},
		"revision": {
			"type": "string",
			"pattern": "^\\d*\\.\\d*\\.\\d*$"
		},
		"description": {
			"type": "string"
		},
		"id": {
			"type": "string"
		},
		"submodels": {
			"type": "object"
		}
	},
	"required": [
		"name",
		"revision",
		"id"
	],
	"definitions": {	
	"name": {
			"type": "string",
			"pattern": "^[A-Za-z_][A-Za-z0-9_]*$",
			"minLength": 3
			}
}
}

=== Jonracwzl/aimfree_models/workshop/validation/resource_information_example.json
{
	"$schema": "../resource_information.json",
	"name": "Kairos_01",
	"id": "ABCDE12345",
	"revision": "0.0.1",
	"submodels": {
		"size": {
			"size": [
				1,
				3
			]
		},
		"state": {
			"current_state": "idle"
		},
		"position": {
			"coordinates": {
				"x": 10,
				"y": 20,
				"z": 0
			}
		}
	}
}
